---
- name: install epel repository
  package:
    name: epel-release
    state: present

- name: Install nagios
  package:
    name: nagios
    state: present

- name: change admin password
  command:
    cmd: /usr/bin/htpasswd -b /etc/nagios/passwd nagiosadmin {{ nagiosadmin_password }} 

- name: Start services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: [ nagios, httpd ]  
